### ISSUE TITLE
Criar layout/design do sistema usando bootstrap

### ISSUE THREAD

**Issue by lucasaciole** [PyLadiesSanca/PyLorean#2]
Usar bootstrap3 para fazer a interface do sistema

**Comment by fcschmidt** [comment]
poderia levar em consideração o uso do mdl ou semantic-ui.

**Comment by lamenezes** [comment]
pensei no bootstrap por ser mais conhecido, mais fácil encontrar pessoas que contribuam

opinião pessoal: não gosto de material design

**Comment by fcschmidt** [comment]
Fazendo! :metal:

**Comment by lamenezes** [comment]
como vc usou bower para instalar as coisas, é necessário colocar no README explicando como instalar o bower e depois como instalar os plugins

**Comment by lamenezes** [comment]
outra coisa: o template deve ficar na pasta pylorean/template

**Comment by lamenezes** [comment]
@fcschmidt vc pode fazer a página inicial do projeto funcionar usando django? assim o pessoal pode rodar o projeto na máquina e ver algo pronto

**Comment by fcschmidt** [comment]
Posso.

**Comment by lamenezes** [comment]
Done in PRs #11 #12 and #13 by @fcschmidt with a little help from me.
